### ISSUE TITLE
ChantModelTest.test_get_concordances behaving strangely

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1427]
While working on #1422, I discovered some unusual behavior with `ChantModelTest.test_get_concordances`:

If I run the entire test suite, this test errors:

```
# python manage.py test main_app.tests
Found 324 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

...quite a lot of output trimmed...

======================================================================
ERROR: test_get_concordances (main_app.tests.test_models.ChantModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/django/cantusdb_project/main_app/tests/test_models.py", line 93, in test_get_concordances
    chant = Chant.objects.get(id=1)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
main_app.models.chant.Chant.DoesNotExist: Chant matching query does not exist.

----------------------------------------------------------------------
Ran 324 tests in 29.551s

FAILED (errors=1, skipped=3)
Destroying test database for alias 'default'...
```

But if I run just `test_models`, the test passes:

```
# python manage.py test main_app.tests.test_models
Found 37 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.....................................
----------------------------------------------------------------------
Ran 37 tests in 0.662s

OK
Destroying test database for alias 'default'...
```

It also passes when I run `python manage.py test main_app.tests.test_models.ChantModelTest` and `python manage.py test main_app.tests.test_models.ChantModelTest.test_get_concordances`.

fwiw, I'm observing this on the develop branch at e3e50552970ad29fe3da34b717365fb585755253

**Comment by jacobdgm** [comment]
Having noted the commit I was at, I realize that something weird has been going on with my git history. I'm confident I've been committing to my branch `1388-suggested-chants`, yet these commits, as well as several made directly on GitHub, are appearing in my `git log` while I'm on my `develop` branch. Going to need to figure out what's going on here...

UPDATE: I deleted my local `develop` branch and pulled again from upstream, and my `git log` seems to have been restored to normal. I ran the tests again with `HEAD` at the proper, most recent commit in `DDMAL:develop`, and updated the initial comment in this issue with the proper commit and the output I'm seeing.
