### ISSUE TITLE
Script to unpack fixtures broken - `ijson` error

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#592]
I'm working through https://github.com/DDMAL/CantusDB/wiki/Getting-Started-with-Development (switching to my postgres14 branch before I start setting up the project) in order to make sure that the version of Postgres I'm using locally matches the version of Postgres running on staging. I'm using the same fixture files I've used several times in the past half year, successfully up until now. But when I run `break_json.py`, I'm getting a new error message:

```
>>> python break_json.py
Traceback (most recent call last):
  File "/code/django/cantusdb_project/break_json.py", line 25, in <module>
    number_of_chants = count_iterator(chants)
  File "/code/django/cantusdb_project/break_json.py", line 20, in count_iterator
    return sum(1 for e in i)
  File "/code/django/cantusdb_project/break_json.py", line 20, in <genexpr>
    return sum(1 for e in i)
ijson.common.IncompleteJSONError: lexical error: invalid char in json text.
          is_last_chant_in_feast": null                     (right here) ------^
```

Some context surrounding the line in question:
```python
# to count how many chants are in the iterator
# to do this, it has to iterate till the end
def count_iterator(i):
    return sum(1 for e in i)


file = open(LARGE_JSON, "rb")
chants = ijson.items(file, "item")
number_of_chants = count_iterator(chants)
print("total chants: ", number_of_chants)  # 492794 chants
```
It seems that when `ijson` tries to iterate through our chant fixture, it runs into some poorly formed json (evidently, an invalid character). Several things I don't understand:
- I and several others have run this script numerous times over the past year and it's worked fine. A specific version number of `ijson` is specified in `requirements.txt`, so this new behavior isn't caused by a version change. Why is it breaking now?
- in the error message, why is `is_last_chant_in_feast": null` missing its opening quotation mark? Why is it missing its final `,` (everywhere I've looked in `chant_fixture.json`, each `"is_last_chant_in_feast"` key is followed by another key, so it should be followed by a comma)?
  - I've searched through `chant_fixture.json`, and there don't appear to be any instances of `is_last_chant_in_feast` that aren't immediately preceded by `"`, or aren't immediately followed by `,`...
-  why is `(right here) ------^` pointing to whitespace following the error message and not to part of the snippet from the json file?

**Comment by jacobdgm** [comment]
UPDATE: it appears one/some of my fixture files may have been corrupted. Whereas I had previously used fixtures copied from a folder on my computer, I tried taking them from an external hard drive, and now the script is running as expected. Not sure exactly what went wrong...
