### ISSUE TITLE
Occasional failure of ChantProofreadViewTest

### ISSUE THREAD

**Issue by PythonSemicolon** [DDMAL/CantusDB#723]
@jacobdgm editing here: We found an intermittently failing test in ChantProofreadViewTest, which we should try to recreate and then fix.

Here's a bit of traceback:
```
======================================================================
ERROR: test_view_url_and_templates (main_app.tests.test_views.ChantProofreadViewTest)
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by jacobdgm** [comment]
With, #1047, we no longer have a Chant Proofread View, and this test no longer exists. I think we're good to close this one!
