### ISSUE TITLE
Request-a-password-reset-link works locally, but not on staging

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#746]
Yesterday, I updated the code running on the staging server. When I tried to request a link to reset my password on staging, I got a 500 internal server error. Looking at the logs, I saw that we had hit a `smtplib.SMTPAuthenticationError: (535, b'Authentication Credentials Invalid')`.

This is baffling, since this works fine when we try locally to send reset emails. We checked on the staging server, and the username and password are correct in the environment variables there. @kqct and I tried generating new AWS credentials, and that didn't help things.

@kqct and I are working to resolve this as quickly as possible.

**Comment by jacobdgm** [comment]
Some traceback:

```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/django/core/mail/__init__.py", line 87, in send_mail
    return mail.send()
  File "/usr/local/lib/python3.9/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 94, in open
    self.connection.login(self.username, self.password)
  File "/usr/local/lib/python3.9/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/local/lib/python3.9/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/usr/local/lib/python3.9/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Authentication Credentials Invalid')
```

**Comment by jacobdgm** [comment]
This is fixed! we were using quotation marks when defining the username and password in our environment variables, and when we imported them into python with `os.getenv`, the quotation marks came along for the ride. Phew!
