### ISSUE TITLE
Test_views are failing

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#817]
```======================================================================
ERROR: test_search_by_title (main_app.tests.test_views.SourceListViewTest)
The "general search" field searches in `title`, `siglum`, `rism_siglum`, `description`, and `summary`
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "changed_initial_password" of relation "users_user" does not exist
LINE 1: ...ity", "country", "website", "full_name", "email", "changed_i...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/django/cantusdb_project/main_app/tests/test_views.py", line 3111, in test_search_by_title
    source = make_fake_source(
  File "/code/django/cantusdb_project/main_app/tests/make_fakes.py", line 380, in make_fake_source
    source.inventoried_by.set([make_fake_user()])
  File "/code/django/cantusdb_project/main_app/tests/make_fakes.py", line 225, in make_fake_user
    user = get_user_model().objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "changed_initial_password" of relation "users_user" does not exist
LINE 1: ...ity", "country", "website", "full_name", "email", "changed_i...
                                                             ^


----------------------------------------------------------------------
Ran 229 tests in 15.183s

FAILED (errors=181)
Destroying test database for alias 'default'...
```

All of the errors mention "changed_initial_password" does not exist. Since #770 is not merged yet it is not the source of the issue.

**Comment by lucasmarchd01** [comment]
Failing in Develop and Staging, Production is fine.

**Comment by lucasmarchd01** [comment]
Solved. "changed_initial_password" was not in the migrations file for users. Not sure why or where this occurred though. Fixing on staging (and local develop)

**Comment by jacobdgm** [comment]
I just ran all the tests locally on the develop branch, and I didn't see this error message. If this is solved, can you close this @lucasmarchd01?
